### ISSUE TITLE
Route parameter identifier

### ISSUE THREAD

**Issue by CWolfs** [mattkol/Chromely#19]
Is there a way to achieve a route like the following...

`this.RegisterGetRequest("/conversations/id:", this.GetConversation);`

where the route will match `id` any value placed after `/conversations` part of the route. For example:

`/conversations/ce20e093-9726-4607-85ac-a8eba25533c1`

Thanks.

**Comment by mattkol** [comment]
Having said all that. I am assuming you run into this because you are doing Ajax requests.

Unless you really need this, I will suggest .NET object bounding (CefSharp) or Message router (CefGlue). Both will allow you pass extra parameter in the parameter property;

.Net object bounding CefSharp

````javascript
boundControllerAsync.getJson("/externalcontroller/movies", parameters, boundObjectResult2);
```` 
Message Router CefGlue:
````javascript
var request = {
      "method": method,
      "url": url
      "parameters": parameters,
      "postData": postData,
 };
```` 

Please see more info in the demos.

**Comment by CWolfs** [comment]
Brilliant. Thank for the reply. I'll use your last reply as that will do the trick for me.

I saw you assumed I was using `CefGlue`. I'm actually using `CefSharp` because it's based off your `React` demo. Is there any issue with using `CefSharp` over `CefGlue`?

**Comment by mattkol** [comment]
Thank you.

I always want to explain using CefGlue, if there is no specific mention of either. Because CefGlue can be used in both .NET/.NET Core -Windows and Linux, So that way I can be sure I cover most grounds. It is just easier if the question is specific.

As far as Chromely is concerned both are the same. The underlying differences/limitations are not changed by Chromely.

There are quite a few discussions on their differences online that should guide developers on what to use.
Some:  [Stackoverflow](https://stackoverflow.com/questions/12224798/any-reason-to-prefer-cefsharp-over-cefglue-or-vice-versa), [CEF Forum](http://magpcss.org/ceforum/viewtopic.php?f=14&t=14927).

**Comment by mattkol** [comment]
Looks like I need to update the angular-react-vue demos. But meanwhile please make a change to Program.cs.

Please see issue #14 

From:
````csharp
class Program
{
   static int Main(string[] args)
   {
      ----
         return new HostEventLoop().Run(window);
     }
  }
}
````
To:
````csharp
class Program
{
   static int Main(string[] args)
   {
      ----
         return new EventLoop().Run(window);
     }
  }
}
````
Will update on repo ASAP too.

**Comment by CWolfs** [comment]
Great - really good work and I appreciate the help. So, if I wanted to support Linux as well I could easily swap to `CefGlue`?

**Comment by mattkol** [comment]
CefGlue can run on both Windows and Linux.
CefSharp is only supported on Windows.

Thanks.

**Comment by CWolfs** [comment]
Great. Thanks a lot. Closing this issue.
