### ISSUE TITLE
Cross Platform as in Mac, Windows, Linux ?

### ISSUE THREAD

**Issue by pushqrdx** [mattkol/Chromely#4]
First i'd like to say 👏 good job on Chromely, Second i like to know whether i can deploy to Mac Os and what is/are the requirements needed.

- [x] Question

**Comment by mattkol** [comment]
"First i'd like to say 👏 good job on Chromely , ..."
Thank you.

No Mac OS is not currently supported. Only Windows and Linux. This is highlighted in README.md. 
"Chromely uses Windows and Linux native GUI API as chromium hosts.", "Cross-platform - Windows, Linux."

But help and contribution is welcome. I am just not familiar with MacOS. As .NET Core is supported in some versions of MacOS this should be possible with CefGlue using [Chromely.CefGlue.Gtk](https://github.com/mattkol/Chromely/tree/master/src/Chromely.CefGlue.Gtk) with some tweak.

For Linux, the project is - [Chromely.CefGlue.Gtk](https://github.com/mattkol/Chromely/tree/master/src/Chromely.CefGlue.Gtk). This runs on both Windows and Linux.

I have been able to run [Chromely.CefGlue.Gtk](https://github.com/mattkol/Chromely/tree/master/src/Chromely.CefGlue.Gtk) on Windows. [Please see](https://github.com/mattkol/Chromely/wiki/Getting-Started-CefGlue-Gtk-(Win)). 

I am however having some issues with running on Linux - no errors, but blank screen. I am not sure quite sure if this is because of the [known issue with CefGlue on Linux](https://bitbucket.org/xilium/xilium.cefglue/issues/108/linux-support) or because of the environment I am testing on. I am using Chromebook. I plan to revisit this with newer version of CefGlue [63.0.3239.132](https://bitbucket.org/xilium/xilium.cefglue/src/ffe89eafa21d70c3ec67a6453bbc0c5f895412be/CefGlue/Interop/version.g.cs?at=default&fileviewer=file-view-default) and a different Linux environment. This is work in progress. But also help is welcome here too.

**Comment by mattkol** [comment]
Recent comment on [CefGlue Linux](https://bitbucket.org/xilium/xilium.cefglue/issues/196/is-it-possible-to-use-net-core-and-deploy) - Comment No. 3

**Comment by mattkol** [comment]
@pushqrdx please see - https://github.com/chromelyapps/Chromely/issues/135
