### ISSUE TITLE
Razor pages

### ISSUE THREAD

**Issue by genifycom** [mattkol/Chromely#42]
In the use case where we want to deliver a ASP.NET Core Web Application locally, Electron works and I have delivered several of these.

The Demo project for Chromely looks great but does not use Razor pages to deliver content.

I am wondering how to make Chromely work with an ASP.NET Core Web Application -> Web Application (i.e. using Razor pages).

It would be great to use Chromely instead of electron.
Do you have any examples of this yet?

Thank you.

**Comment by mattkol** [comment]
_"In the use case where we want to deliver a ASP.NET Core Web Application locally, Electron works and I have delivered several of these."_

This is possible because you are likely hosting ASP.NET Core Web app in Electron or hosting them side by side and using REST to communicate.

From Electron.NET:
_"Electron.NET is a wrapper around a "normal" Electron application with an **embedded** ASP.NET Core application. Via our Electron.NET IPC bridge we can invoke Electron APIs from .NET."_

Chromely is not structured that way. 

I do not have an example using Razor. I honestly have not looked closely yet, but as long as you can precompile your frontend into a bundle understood by chrome, it should be fine. Though not really comparing apples to apples, the same approach with Angular, React and Vue can be used. Please see more in [Chromely-Apps](https://github.com/mattkol/Chromely/wiki/Chromely-Apps).

All Chromely requires from such bundle is an html entry file.

I also see some implementation of Razor being used outside ASP.NET. Those approaches can be useful too.
