### ISSUE TITLE
Improvement Suggestion

### ISSUE THREAD

**Issue by aammfe** [mattkol/Chromely#52]
First of all Thanks for creating this beautiful library 👏 and Thanks for understanding .net people inner thoughts 👍 

Unfortunately from Doc look like Chormely does not work on mac.
May I suggest you a solution.
[Avalonia](https://github.com/AvaloniaUI/Avalonia)  Most popular .net core UI it [build](https://dev.azure.com/AvaloniaUI/AvaloniaUI/_build/results?buildId=989) successfully on mac as well, It has a  Chromium Embedded Framework ([CEF](https://github.com/VitalElement/CefGlue.Core)) By using It there should be no issue with builds.
I think Its most stable way for chromely.

Please share your thoughts on it.

**Comment by mattkol** [comment]
@aammfe first thanks for the compliment.

Thanks for bringing up Avalonia. It was one of the earlier projects I considered along with [LibUI](https://github.com/andlabs/libui) and [Nana C++](http://nanapro.org/en-us/). They are all active and stable frameworks. Except for Nana that is only for Windows and Linux, others are full cross platform. But as a .NET focused project Avalonia seem the right choice. But Avalonia (**without changes**) does not meet core Chromely requirement. Chromely is designed to be a full-fledged browser to be hosted in the "thinnest" window host possible. I tried at the time to make skinny windows out of Avalonia, but the deeper I get the more work required.

When I discovered [Winapi](https://github.com/prasannavl/WinApi), I decided to go with that as that allows for an easier "thin" window extraction. I meant it as a first trial with the hope of getting back to a true cross platform framework like Avalonia and LibUI. I hope to refocus on a true cross platform again, as soon as I get the some bandwidth, but as you can see, the way the project is currently there is always something to work on. 

However, please note that it will not be advisable to use Avalonia as-is currently, because it is a complete UI framework and that would be like embedding chromium into an existing application instead of it being a standalone app. This is why it is noted in ReadMe ----  **"It is focused on building apps based on Xilium.CefGlue, CefSharp implementations of embedded Chromium (Cef) without WinForms or WPF.". "**

**... without WinForms or WPF ...**

If this is done, then developers will expect that actual Avalonia controls usage are supported. First this defeats core Chromely purpose and may take focus away from core Chromely functionalities.

**Comment by aammfe** [comment]
how will you make it cross platform
you have plans?
Please share.

For short term and as a complete solution for community I think its better to stand on giant shoulder.

Avalonia can be used and as time goes thin layer can be extracted.

This way crossplatfrom issue can be resolve quickly.

then new features can be added on top.

right now chormely can not be used as election bcs of its cross platform issue.

Please do consider it.
