### ISSUE TITLE
Fullscreen Not working CefGlue Gtk (Linux) Version 68

### ISSUE THREAD

**Issue by WSpadaro** [mattkol/Chromely#60]
I have been developing against the "old" dll's provided in issue #48 and wanted to ask about the ability to close the window and open a new one after one is already opened; however, before making a new post I wanted to make sure I had the newest code. I updated to CefGlue Version 68 and tried testing the code and it appears that the full-screen functionality no longer works. Using the following code does not create a full-screen window.
``` csharp
            string startUrl = "http://www.google.com";
            ChromelyConfiguration config = ChromelyConfiguration
                                          .Create()
                                          .WithHostTitle("chromely")
                                          .WithAppArgs(args)
                                          .WithStartUrl(startUrl)
                                          .WithHostMode(Chromely.Core.Host.WindowState.Fullscreen, false)
                                          .WithHostSize(1280, 1024)

                                           //Set multi-threaded_message_loop false
                                           //only supported on windows
                                           .WithCustomSetting(CefSettingKeys.MultiThreadedMessageLoop, false)

                                           .WithCommandLineArg("disable-gpu", "1")
                                           .WithCommandLineArg("disable-gpu-compositing", "1")
                                           .WithCommandLineArg("disable-smooth-scrolling", "1")
                                           .WithCommandLineArg("no-sandbox", "1");

            using (app = new CefGlueBrowserWindow(config))
            {
                return app.Run(args);
            }
```
When run, this creates a non-full-screen window in which the browser never loads.

2018-12-17 12:36:01.688 [INFO] CefRuntime.ExecuteProcess() returns -1
[1217/123602.755251:ERROR:gpu_process_transport_factory.cc(1026)] Lost UI shared context.

DevTools listening on ws://127.0.0.1:20480/devtools/browser/4f0f3d7c-c08b-4571-9806-f4f781b27f9b
[1217/123603.015621:ERROR:backend_impl.cc(1423)] Unable to map Index file
[1217/123603.038694:ERROR:backend_impl.cc(1423)] Unable to map Index file
[1217/123603.043017:ERROR:disk_cache.cc(169)] Unable to create cache
[1217/123603.044592:ERROR:shader_disk_cache.cc(600)] Shader Cache Creation failed: -2
[1217/123603.591586:ERROR:service_manager_context.cc(250)] Attempting to run unsupported native service: /home/wesley/Shared/Chromely - Copy/publish/content_renderer.service
[1217/123604.266971:ERROR:sandbox_linux.cc(378)] InitializeSandbox() called with multiple threads in process gpu-process.

The output appears to be the same problem occurring with the original update.

**Comment by mattkol** [comment]
If this is caused by an upgrade/higher version, it is likely due to a change in CEF or CefGlue. Always a tough thing to get the right documentation as there are no comprehensive release notes. One has to got through commits to see what has  changed. I noticed a recent change on CEF related to [Sandbox](https://bitbucket.org/chromiumembedded/cef/diff/tests/cefsimple/cefsimple_linux.cc?diff2=dec98a5534e1&at=3578#Ltests/cefsimple/cefsimple_linux.ccT52). May be the commandline option is no longer required. Not sure, I have to dig more. So I will remove - .WithCommandLineArg("no-sandbox", "1"); first and see. By default NoSandbox is "true".

If you have the time though, my suggestion is to try v66 and v68 with the same code base and see if is a version issue. If a version issue then one can see what has changed, if not then it will be a bug that we can track.

Attached is solution with v66 and v68, if you can see what you find. Note that v66 has no fullscreen option.
[GtkLinuxTester.zip](https://github.com/mattkol/Chromely/files/2693110/GtkLinuxTester.zip)
